server:
  port: 8081

spring:
  application:
    name: CarbonTracker

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/carbontracker}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:changeme}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true